# Generated by Django 4.2.6 on 2023-12-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0001_initial'),
        ('posts', '0002_tags_description_tags_iconify_string_tags_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='publishable',
            field=models.ManyToManyField(blank=True, to='generics.publishable'),
        ),
    ]
