# Generated by Django 4.2.6 on 2023-10-20 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0002_rename_like_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polymorphiclike',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
    ]
