# Generated by Django 4.2.6 on 2023-12-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0001_initial'),
        ('posts', '0003_post_slug_alter_tags_publishable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publishable',
            field=models.ManyToManyField(blank=True, to='generics.publishable'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=450, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
