# Generated by Django 4.2.6 on 2023-10-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_polymorphiccomments_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
