# Generated by Django 4.2.6 on 2023-10-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_polymorphiclike_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='polymorphiclike',
            unique_together=set(),
        ),
    ]
