# Generated by Django 4.2.6 on 2023-10-20 16:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0007_alter_polymorphiclike_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='polymorphiclike',
            unique_together={('user', 'object_id', 'content_type')},
        ),
    ]
