# Generated by Django 4.2.6 on 2023-12-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishable',
            name='last_viewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publishable',
            name='viewer_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
